services:
  mongodb:
    image: mongo:6.0
    container_name: scriptdb_mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: scriptdb
    volumes:
      - ./mongo_data:/data/db
