services:
  mongodb:
    image: mongo:6.0
    container_name: scriptdb_mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: scriptdb
    volumes:
      - ./mongo_data:/data/db
  redis:
    image: redis:7.2    # 选择官方最新版
    container_name: scriptdb_redis
    ports:
      - "6379:6379"     # 把容器里的6379端口映射到本地
    volumes:
      - ./redis_data:/data # 持久化数据
    restart: unless-stopped

